apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app-deployment
        image: karthikeyanmcloud/simplenodeapp:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  ports:
    - port: 3002
  type: LoadBalancer
  selector:
    app: node-app
